### ISSUE TITLE
0.4 Compatibility

### ISSUE THREAD

**Issue by one-more-minute** [jakebolewski/JuliaParser.jl#17]
Right now JuliaParser.jl fails its tests on 0.4, it'd be great to see that change as it's one of the major sticking points for Juno on 0.4.

**Comment by jakebolewski** [comment]
I know of one test edge case that fails, but it can parse all of base and Tim Holy is using it for package coverage and experimental coverage reports against latest master.  I you tried it recently?

**Comment by one-more-minute** [comment]
My bad – it's been a little while and I completely forgot to `Pkg.update()`. Thanks!
