### ISSUE TITLE
0.4 failure (in defining parse function)

### ISSUE THREAD

**Issue by stevengj** [jakebolewski/JuliaParser.jl#18]
With 0.4, this is now giving:
```
ERROR: LoadError: error in method definition: function Base.parse must be explicitly imported to be extended
 in include at ./boot.jl:250
 in include_from_node1 at ./loading.jl:129
 in include at ./boot.jl:250
 in include_from_node1 at ./loading.jl:129
 in reload_path at ./loading.jl:153
 in _require at ./loading.jl:68
 in require at ./loading.jl:51
 in include at ./boot.jl:250
 in include_from_node1 at ./loading.jl:129
while loading /Users/stevenj/.julia/JuliaParser/src/parser.jl, in expression starting on line 1864
while loading /Users/stevenj/.julia/JuliaParser/src/JuliaParser.jl, in expression starting on line 6
while loading /Users/stevenj/.julia/JuliaParser/test/runtests.jl, in expression starting on line 1
```
Frankly, I don't understand the source of this issue.   Isn't it valid to define a `JuliaParser.parse` function that shadows `Base.parse` without extending it?  (After all, this error about importing before extending was added in 2012: JuliaLang/julia@289c6dfdaa348f801b04cbbf916ff09c8ce3b80a.)

Presumably, something has recently changed about `Base.parse` that suddenly makes Julia interpret the `JuliaParser.parse` as an extension of the same function rather than as a declaration of a new function in the `JuliaParser` namespace?   (The issue is not that `JuliaParser/src/parser.jl` does `export parse`, since I get the same error if I comment out that line.)

@JeffBezanson, @vtjnash?

**Comment by stevengj** [comment]
Note that this is apparently causing `Coverage` to fail, which is cascading into a lot of Travis failures on other projects.

**Comment by staticfloat** [comment]
Yep, I can confirm the same thing killing the [buildbot Base coverage tests](http://buildbot.e.ip.saba.us:8010/builders/coverage_ubuntu14.04-x64/builds/305/steps/Gather%20inlined%20test%20results/logs/stdio).

**Comment by jakebolewski** [comment]
Fixed by https://github.com/JuliaLang/julia/commit/3d37c866fe9f7590684e4348d3ce853f4b7a5be2.
